export const FETCH_PARAMS = "FETCH_PARAMS";
export const FETCH_PARAMS_SUCCEEDED = "FETCH_PARAMS_SUCCEEDED";
export const FETCH_PARAMS_FAILED = "FETCH_PARAMS_FAILED";

export const ADD_PARAM = "ADD_PARAM";
export const ADD_PARAM_SUCCEEDED = "ADD_PARAM_SUCCEEDED";
export const ADD_PARAM_FAILED = "ADD_PARAM_FAILED";

export const RENAME_PARAM = "RENAME_PARAM";
export const RENAME_PARAM_SUCCEEDED = "RENAME_PARAM_SUCCEEDED";
export const RENAME_PARAM_FAILED = "RENAME_PARAM_FAILED";

export const DELETE_PARAM = "DELETE_PARAM"
export const DELETE_PARAM_SUCCEEDED = "DELETE_PARAM_SUCCEEDED"
export const DELETE_PARAM_FAILED = "DELETE_PARAM_FAILED"
