# docker-compose up
version: '2.1'
services:

  postgres:
    image: "postgres:10.1"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      #POSTGRES_DB: default
    #volumes:
      #-

  web:
    build: .  # use Dockerfile in current dir
    ports:
     - "80:8080"  # proxy internal port 8080 as 80
    volumes:
     - .:/app  # mounting current dir inside volume, autochange
    depends_on:
      - postgres
