export const ADD_TEAM = "ADD_TEAM";
export const UPDATE_TEAM_NAME = "UPDATE_TEAM_NAME";

export const ADD_TEAM_ROLE = "ADD_TEAM_ROLE"

export const FETCH_TEAMS_ROLES = "FETCH_TEAMS_ROLES"
export const TEAMS_ROLES_SUCCEEDED = "TEAMS_ROLES_SUCCEEDED"
export const TEAMS_ROLES_FAILED = "TEAMS_ROLES_FAILED"
