export const ADD_TEAM = "ADD_TEAM";
export const ADD_TEAM_SUCCEEDED = "ADD_TEAM_SUCCEEDED";
export const ADD_TEAM_FAILED = "ADD_TEAM_FAILED";

export const UPDATE_TEAM_NAME = "UPDATE_TEAM_NAME";
export const UPDATE_TEAM_NAME_SUCCEEDED = "UPDATE_TEAM_NAME_SUCCEEDED";
export const UPDATE_TEAM_NAME_FAILED = "UPDATE_TEAM_NAME_FAILED";

export const FETCH_TEAMS_ROLES = "FETCH_TEAMS_ROLES"
export const TEAMS_ROLES_SUCCEEDED = "TEAMS_ROLES_SUCCEEDED"
export const TEAMS_ROLES_FAILED = "TEAMS_ROLES_FAILED"

export const ADD_TEAM_ROLE = "ADD_TEAM_ROLE"
export const ADD_TEAM_ROLE_SUCCEEDED = "ADD_TEAM_ROLE_SUCCEEDED"
export const ADD_TEAM_ROLE_FAILED = "ADD_TEAM_ROLE_FAILED"

export const DELETE_TEAM_ROLE = "DELETE_TEAM_ROLE"
export const DELETE_TEAM_ROLE_SUCCEEDED = "DELETE_TEAM_ROLE_SUCCEEDED"
export const DELETE_TEAM_ROLE_FAILED = "DELETE_TEAM_ROLE_FAILED"

export const DELETE_TEAM = "DELETE_TEAM"
export const DELETE_TEAM_SUCCEEDED = "DELETE_TEAM_SUCCEEDED"
export const DELETE_TEAM_FAILED = "DELETE_TEAM_FAILED"


