export const ADD_TEAM = "ADD_TEAM";
export const ADD_TEAM_SUCCEEDED = "ADD_TEAM_SUCCEEDED";
export const ADD_TEAM_FAILED = "ADD_TEAM_FAILED";

export const RENAME_TEAM = "RENAME_TEAM";
export const RENAME_TEAME_SUCCEEDED = "RENAME_TEAME_SUCCEEDED";
export const RENAME_TEAM_FAILED = "RENAME_TEAM_FAILED";

export const FETCH_TEAMS_ROLES = "FETCH_TEAMS_ROLES"
export const TEAMS_ROLES_SUCCEEDED = "TEAMS_ROLES_SUCCEEDED"
export const TEAMS_ROLES_FAILED = "TEAMS_ROLES_FAILED"

export const ADD_TEAM_ROLE = "ADD_TEAM_ROLE"
export const ADD_TEAM_ROLE_SUCCEEDED = "ADD_TEAM_ROLE_SUCCEEDED"
export const ADD_TEAM_ROLE_FAILED = "ADD_TEAM_ROLE_FAILED"

export const DELETE_TEAM_ROLE = "DELETE_TEAM_ROLE"
export const DELETE_TEAM_ROLE_SUCCEEDED = "DELETE_TEAM_ROLE_SUCCEEDED"
export const DELETE_TEAM_ROLE_FAILED = "DELETE_TEAM_ROLE_FAILED"

export const DELETE_TEAM = "DELETE_TEAM"
export const DELETE_TEAM_SUCCEEDED = "DELETE_TEAM_SUCCEEDED"
export const DELETE_TEAM_FAILED = "DELETE_TEAM_FAILED"


