export const ADD_ROLE = "ADD_ROLE";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_PERSON = "ADD_PERSON";

export const ADD_PARAM = "ADD_PARAM"

export const UPDATE_PARAM = "UPDATE_PARAM";
export const UPDATE_SKILL_LEVEL = "UPDATE_SKILL_LEVEL";
export const UPDATE_PERSON_NAME = "UPDATE_PERSON_NAME";
export const UPDATE_ROLE_NAME = "UPDATE_ROLE_NAME";
export const UPDATE_SKILL_NAME = "UPDATE_SKILL_NAME";

export const UPDATE_PARAM_NAME = "UPDATE_PARAMETER_NAME";

export const ADD_PARAM_PERSON = "ADD_PARAM_PERSON"
export const ADD_SKILL_PERSON = "ADD_SKILL_PERSON"
/**/
export const ADD_PERSON_ROLE = "ADD_PERSON_ROLE"
export const ADD_PERSON_TEAM = "ADD_PERSON_TEAM"

export const DELETE_ROW_FROM_MODEL = "DELETE_ROW_FROM_MODEL"

export const INIT_STATE = "INIT_STATE";
export const INIT_STATE_SUCCEEDED = "INIT_STATE_SUCCEEDED";
export const INIT_STATE_FAILED = "INIT_STATE_FAILED";
