export const ADD_ROLE = "ADD_ROLE";
export const ADD_SKILL = "ADD_SKILL";
export const ADD_PERSON = "ADD_PERSON";
export const ADD_TEAM = "ADD_TEAM";
export const ADD_PARAM = "ADD_PARAM"

export const UPDATE_PARAM = "UPDATE_PARAM";
export const UPDATE_SKILL_LEVEL = "UPDATE_SKILL_LEVEL";
export const UPDATE_PERSON_NAME = "UPDATE_PERSON_NAME";
export const UPDATE_ROLE_NAME = "UPDATE_ROLE_NAME";
export const UPDATE_SKILL_NAME = "UPDATE_SKILL_NAME";
export const UPDATE_TEAM_NAME = "UPDATE_TEAM_NAME";
export const UPDATE_PARAM_NAME = "UPDATE_PARAMETER_NAME";

export const ADD_PARAM_PERSON = "ADD_PARAM_PERSON"
export const ADD_SKILL_PERSON = "ADD_SKILL_PERSON"
export const ADD_TEAM_ROLE = "ADD_TEAM_ROLE"
export const ADD_PERSON_ROLE = "ADD_PERSON_ROLE"

export const DELETE_ROW_FROM_MODEL = "DELETE_ROW_FROM_MODEL"
