export const FETCH_PERSONS = "FETCH_PERSONS";
export const FETCH_PERSONS_SUCCEEDED = "FETCH_PERSONS_SUCCEEDED";
export const FETCH_PERSONS_FAILED = "FETCH_PERSONS_FAILED";

export const ADD_PERSON = "ADD_PERSON";
export const ADD_PERSON_SUCCEEDED = "ADD_PERSON_SUCCEEDED";
export const ADD_PERSON_FAILED = "ADD_PERSON_FAILED";

export const RENAME_PERSON = "RENAME_PERSON";
export const RENAME_PERSONE_SUCCEEDED = "RENAME_PERSONE_SUCCEEDED";
export const RENAME_PERSON_FAILED = "RENAME_PERSON_FAILED";

export const DELETE_PERSON = "DELETE_PERSON"
export const DELETE_PERSON_SUCCEEDED = "DELETE_PERSON_SUCCEEDED"
export const DELETE_PERSON_FAILED = "DELETE_PERSON_FAILED"
