# Generated by Django 2.1 on 2018-08-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_management', '0003_auto_20180819_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Jr', 'Junior'), ('Mdl', 'Middle'), ('Sr', 'Senior'), ('Pl', 'Principal'), ('Ld', 'Lead')], max_length=2),
        ),
    ]
