export const FETCH_SKILLS = "FETCH_SKILLS";
export const FETCH_SKILLS_SUCCEEDED = "FETCH_SKILLS_SUCCEEDED";
export const FETCH_SKILLS_FAILED = "FETCH_SKILLS_FAILED";

export const ADD_SKILL = "ADD_SKILL";
export const ADD_SKILL_SUCCEEDED = "ADD_SKILL_SUCCEEDED";
export const ADD_SKILL_FAILED = "ADD_SKILL_FAILED";

export const RENAME_SKILL = "RENAME_SKILL";
export const RENAME_SKILL_SUCCEEDED = "RENAME_SKILL_SUCCEEDED";
export const RENAME_SKILL_FAILED = "RENAME_SKILL_FAILED";

export const DELETE_SKILL = "DELETE_SKILL"
export const DELETE_SKILL_SUCCEEDED = "DELETE_SKILL_SUCCEEDED"
export const DELETE_SKILL_FAILED = "DELETE_SKILL_FAILED"
