export const FETCH_ROLES = "FETCH_ROLES";
export const FETCH_ROLES_SUCCEEDED = "FETCH_ROLES_SUCCEEDED";
export const FETCH_ROLES_FAILED = "FETCH_ROLES_FAILED";

export const ADD_ROLE = "ADD_ROLE";
export const ADD_ROLE_SUCCEEDED = "ADD_ROLE_SUCCEEDED";
export const ADD_ROLE_FAILED = "ADD_ROLE_FAILED";

export const RENAME_ROLE = "RENAME_ROLE";
export const RENAME_ROLE_SUCCEEDED = "RENAME_ROLE_SUCCEEDED";
export const RENAME_ROLE_FAILED = "RENAME_ROLE_FAILED";

export const DELETE_ROLE = "DELETE_ROLE"
export const DELETE_ROLE_SUCCEEDED = "DELETE_ROLE_SUCCEEDED"
export const DELETE_ROLE_FAILED = "DELETE_ROLE_FAILED"
